<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

class AssetFactory extends Factory
{
    private static $index = 0;

    public function definition()
    {
        $assets = [
            [
                'name' => 'Bitcoin',
                'code' => 'BTCUSDT',
                'yahoo_code' => 'BTC-USD',
                'image' => 'crypto/btc.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Ethereum',
                'code' => 'ETHUSDT',
                'yahoo_code' => 'ETH-USD',
                'image' => 'crypto/eth.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Cardano',
                'code' => 'ADAUSDT',
                'yahoo_code' => 'ADA-USD',
                'image' => 'crypto/ada.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'XRP',
                'code' => 'XRPUSDT',
                'yahoo_code' => 'XRP-USD',
                'image' => 'crypto/xrp.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2
            ],
            [
                'name' => 'AVAX',
                'code' => 'AVAXUSDT',
                'yahoo_code' => 'AVAX-USD',
                'image' => 'crypto/avax.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'FTM',
                'code' => 'FTMUSDT',
                'yahoo_code' => 'FTM-USD',
                'image' => 'crypto/ftm.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Solana',
                'code' => 'SOLUSDT',
                'yahoo_code' => 'SOL-USD',
                'image' => 'crypto/sol.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Litecoin',
                'code' => 'LTCUSDT',
                'yahoo_code' => 'LTC-USD',
                'image' => 'crypto/ltc.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Gala',
                'code' => 'GALAUSDT',
                'yahoo_code' => 'GALA-USD',
                'image' => 'crypto/gala.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Internet Computer',
                'code' => 'ICPUSDT',
                'yahoo_code' => 'ICP-USD',
                'image' => 'crypto/icp.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Flow',
                'code' => 'FLOWUSDT',
                'yahoo_code' => 'FLOW-USD',
                'image' => 'crypto/flow.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Terra Classic',
                'code' => 'LUNCUSDT',
                'yahoo_code' => 'LUNC-USD',
                'image' => 'crypto/luna.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Ravencoin',
                'code' => 'RVNUSDT',
                'yahoo_code' => 'RVN-USD',
                'image' => 'crypto/rvn.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Filecoin',
                'code' => 'FILUSDT',
                'yahoo_code' => 'FIL-USD',
                'image' => 'crypto/fil.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Klaytn',
                'code' => 'KLAYUSDT',
                'yahoo_code' => 'KLAY-USD',
                'image' => 'crypto/klay.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'MyNeighborAlice',
                'code' => 'ALICEUSDT',
                'yahoo_code' => 'ALICE-USD',
                'image' => 'crypto/alice.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'DigiByte',
                'code' => 'DGBUSDT',
                'yahoo_code' => 'DGB-USD',
                'image' => 'crypto/dgb.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Gold',
                'code' => 'XAUUSDT',
                'yahoo_code' => 'GC=F',
                'image' => 'commodities/gold.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Silver',
                'code' => 'XAGUSDT',
                'yahoo_code' => 'SI=F',
                'image' => 'commodities/silver.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Oil',
                'code' => 'WTIUSDT',
                'yahoo_code' => 'CL=F',
                'image' => 'commodities/oil.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Natural Gas',
                'code' => 'NGUSDT',
                'yahoo_code' => 'NG=F',
                'image' => 'commodities/natural-gas.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Corn',
                'code' => 'CORNUSDT',
                'yahoo_code' => 'ZC=F',
                'image' => 'commodities/corn.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Soybeans',
                'code' => 'SOYUSDT',
                'yahoo_code' => 'ZS=F',
                'image' => 'commodities/soybeans.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Wheat',
                'code' => 'WHEATUSDT',
                'yahoo_code' => 'ZW=F',
                'image' => 'commodities/wheat.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Cotton',
                'code' => 'COTTONUSDT',
                'yahoo_code' => 'CT=F',
                'image' => 'commodities/cotton.png',
                'category' => 'commodities',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Pepemon',
                'code' => 'PEPEUSDT',
                'yahoo_code' => 'PEPE24478-USD',
                'image' => 'crypto/pepe.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Shiba Inu',
                'code' => 'SHIBUSDT',
                'yahoo_code' => 'SHIB-USD',
                'image' => 'crypto/shib.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
            [
                'name' => 'Dogecoin',
                'code' => 'DOGEUSDT',
                'yahoo_code' => 'DOGE-USD',
                'image' => 'crypto/doge.png',
                'category' => 'crypto',
                'price_precision' => 2,
                'quantity_precision' => 2,
                'quote_precision' => 2,
            ],
        ];

        return $assets[self::$index++];
    }
}
